Using Docker
Azazel-h/Fabry-Perot_Interferometer pull request #26
Opened 2022-11-02 17:51 UTC by UncleDrema

2022-11-03 11:54 UTC, Azazel-h requested changes

2022-11-03 11:54 UTC, Azazel-h commented on README.md
> +1. Поставить docker
Напишешь снизу просто список команд?

2022-11-03 11:54 UTC, Azazel-h commented on README.md
> +2. Установить образ python командой *docker pull python*
А вот если был бы docker-compose можно было бы автоматически зависимости скачивать)

2022-11-03 22:19 UTC, UncleDrema commented on README.md
> +2. Установить образ python командой *docker pull python*
Не стоит того

2022-11-03 22:19 UTC, UncleDrema commented on README.md
> +1. Поставить docker
Ага, чуть позже

2022-11-04 09:06 UTC, UncleDrema commented on README.md
> +1. Поставить docker
Готово

2022-11-04 09:29 UTC, Azazel-h approved these changes

2022-11-04 09:29 UTC, merged