del logo zoom out pan
Azazel-h/Fabry-Perot_Interferometer pull request #28
Opened 2022-11-03 12:21 UTC by RicKinG3

2022-11-12 07:54 UTC, Azazel-h requested changes
Таск не выполнен..
Ты же просто кнопку убрал, но отдаление мышкой все еще работает.
<img width="565" alt="Снимок экрана 2022-11-12 в 10 54 02" src="https://user-images.githubusercontent.com/40645311/201464624-74865ed8-7622-4148-a1b0-914e940b20de.png">

2022-11-12 09:10 UTC, RicKinG3 commented
Ля ща исправлю

сб, 12 нояб. 2022 г., 10:55 Yasuhiro ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Таск не выполнен..
> Ты же просто кнопку убрал, но отдаление мышкой все еще работает.
> [image: Снимок экрана 2022-11-12 в 10 54 02]
> <https://user-images.githubusercontent.com/40645311/201464624-74865ed8-7622-4148-a1b0-914e940b20de.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Azazel-h/Fabry-Perot_Interferometer/pull/28#pullrequestreview-1178057960>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVTA3OORYPAT2DUOBMW6AF3WH5EN5ANCNFSM6AAAAAARWCPDDY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-17 11:56 UTC, RicKinG3 commented
усе удалил полностью зум

2022-11-17 16:55 UTC, sersoid commented on fabry_perot/views.py
> +    config = {'displaylogo': False,'scrollZoom': False, 'Zoom': True, 'toImageButtonOptions': {'height': None, 'width': None}, 'modeBarButtonsToRemove': ['zoomOut2d', 'pan']}
Бесполезный параметр Zoom, нужно убрать.

Также можно убрать scrollZoom и modeBarButtonsToRemove, т.к. вызывается update_xaxes/update_yaxes с параметром fixedrange=True.

2022-11-17 16:59 UTC, Sersoid commented on michelson/views.py
> +    config = {'displaylogo': False, 'scrollZoom' : False, 'modeBarButtonsToRemove': ['zoomOut2d', 'pan', 'zoom']}
Аналогично Фабри-Перо удалить scrollZoom и modeBarButtonsToRemove.

Желательно добавить toImageButtonOptions.

2022-11-17 22:10 UTC, Azazel-h commented on fabry_perot/views.py
> +    fig = px.imshow(intensity, color_continuous_scale=['#000000',sll.color.rgb_to_hex(sll.wave.wave_length_to_rgb(wave_length / sll.nm))])
Откуда взялся sll на этой ветке? Его тут нет. Работать не должно

2022-11-17 22:10 UTC, Azazel-h requested changes

2022-11-17 22:10 UTC, Azazel-h commented on fabry_perot/views.py
> +    fig = px.imshow(intensity, color_continuous_scale=['#000000',sll.color.rgb_to_hex(sll.wave.wave_length_to_rgb(wave_length / sll.nm))])
Откуда взялся sll на этой ветке? Его тут нет. Работать не должно

2022-11-21 06:29 UTC, closed without merging