Database call optimization and docker rewrite
Azazel-h/Fabry-Perot_Interferometer pull request #45
Opened 2022-11-22 19:06 UTC by Sersoid

2022-11-26 11:09 UTC, Azazel-h requested changes

2022-11-26 11:09 UTC, Azazel-h commented on fabry_perot/views.py
> -        form_dict['user'] = request.user
<img width="681" alt="Снимок экрана 2022-11-26 в 13 39 37" src="https://user-images.githubusercontent.com/40645311/204084594-6487b265-66ba-457c-871e-7f4dc2896b5a.png">

2022-11-26 11:09 UTC, Azazel-h commented on fabry_perot/views.py
> +        context.update({'array_of_reqs': RequestFP.objects.filter(user=request.user.username)[:5:-1]})
И еще раз

2022-11-26 11:09 UTC, Azazel-h commented on fabry_perot/views.py
> +                form_dict.update({'user': request.user.username})
И еще разок

2022-11-26 11:09 UTC, Azazel-h commented on fabry_perot/views.py
> +        context.update({'presets': PresetFP.objects.filter(user=request.user.username)[::-1]})
Мехххх

2022-11-26 11:09 UTC, Azazel-h commented on interferometers/settings.py
> -    'django.middleware.security.SecurityMiddleware',
Зачем мидалварь безопасности выкинул?

2022-11-26 11:09 UTC, Azazel-h commented on michelson/views.py
> +        context.update({'presets': PresetM.objects.filter(user=request.user.username)[::-1]})
Ну ты уже все понял про .update

2022-11-26 11:09 UTC, Azazel-h commented on michelson/views.py
> +                form_dict.update({'user': request.user.username})
И тут

2022-11-26 11:09 UTC, Azazel-h commented on michelson/views.py
> +        context.update({'presets': PresetM.objects.filter(user=request.user.username)[::-1]})
И даже тут

2022-11-26 11:09 UTC, Azazel-h commented on README.md
> +$ docker pull python
Он вроде сам все скачает, разве нет?

2022-11-26 11:09 UTC, Azazel-h commented on README.md
> +$ docker-compose up
Билдить не надо?

2022-11-26 11:09 UTC, Azazel-h commented on docker-compose.yml
> +      - .:/app
Если сможешь решить проблему с интеграцией sqlite3 в докер, будет чудненько

2022-11-26 11:19 UTC, Sersoid commented on docker-compose.yml
> +      - .:/app
а в чём проблема текущего sqlite?

2022-11-26 11:20 UTC, Sersoid commented on README.md
> +$ docker-compose up
Нет, при вызове `up` автоматически проверяется наличие собранного контейнера и, если его нет, то собирает его

2022-11-26 11:21 UTC, Sersoid commented on README.md
> +$ docker pull python
Да, можно убрать

2022-11-26 11:21 UTC, Azazel-h commented on docker-compose.yml
> +      - .:/app
Основная проблема этой связки в контейнеризации.
Тк тебе не нужно отдельный образ для sqllite он воспринимает бд, как обычный файлик и не сохраняет изменения + нельзя подключится из вне

2022-11-26 11:22 UTC, Sersoid commented on fabry_perot/views.py
> -        form_dict['user'] = request.user
Я ебло, ща исправлю

2022-11-26 11:36 UTC, Sersoid commented on docker-compose.yml
> +      - .:/app
Хорошо, попробую сделать.

2022-11-26 11:43 UTC, Sersoid commented on interferometers/settings.py
> -    'django.middleware.security.SecurityMiddleware',
А мы его вообще используем? Я бы понял, если бы у нас ssl был или пользователи загружали какие-то конфеденциальные файлы, но у нас этого нет.

2022-11-26 11:43 UTC, Sersoid commented on interferometers/settings.py
> -    'django.middleware.security.SecurityMiddleware',
Могу вернуть конечно, но хз зачем

2022-11-26 11:47 UTC, Azazel-h commented on interferometers/settings.py
> -    'django.middleware.security.SecurityMiddleware',
<img width="823" alt="Снимок экрана 2022-11-26 в 14 45 57" src="https://user-images.githubusercontent.com/40645311/204087112-05a4ec56-a74f-45fd-8abf-db7a9f2e768f.png">

Как только пойдет проброс файлов, он вполне может пригодиться + сертификат вроде как на хосте есть

2022-11-27 17:23 UTC, Azazel-h approved these changes

2022-11-27 17:23 UTC, merged